### ISSUE TITLE
Signing of transaction should be possible with partial set of keys

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb-common#13]
This method: https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L435

Currently, a transaction can just be signed using all the corresponding private keys.
In a real-life scenario this is often unpractical. Hence, `Transaction.sign` should accept a partial set of keys to sign a transaction (while still be (de)serializable `to_dict`, `from_dict`).

**Comment by TimDaub** [comment]
We'll also have to make adjustments to cryptoconditions: https://github.com/bigchaindb/cryptoconditions/pull/25

**Comment by r-marques** [comment]
This issue was moved to bigchaindb/bigchaindb#729
