### ISSUE TITLE
`owners_before` and `owners_after` should be derived from Cryptoconditions

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb-common#15]
@diminator gave a hint here: https://github.com/bigchaindb/bigchaindb-common/pull/4#r76391859

**Comment by diminator** [comment]
this will be troublesome/impossible for `Thresholdconditions` as the internals are masked, can only be done for `Fulfillments`

note that `owners_before` and `owners_after` are required mainly for:
- indexing
- `get_owned_ids`

**Comment by r-marques** [comment]
This issue was moved to bigchaindb/bigchaindb#728
