### ISSUE TITLE
Remove unnecessary exceptions

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb-common#23]
Haven't double checked all of them, but a large number of the [exceptions](https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/exceptions.py) could be removed since they're BDB-specific.

**Comment by sbellem** [comment]
:+1:

**Comment by r-marques** [comment]
This issue was moved to bigchaindb/bigchaindb#723
