### ISSUE TITLE
Integrate digital asset

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb-common#24]
In response to https://github.com/bigchaindb/bigchaindb/pull/599 (which are the specs for this ticket).

TODOs:
- Rename `payload` to `metadata`
- Implement Asset class
- Integrate Assets into `Transaction.create` and `Transaction.transfer`
- Integrate Assets into Transaction constructor

//cc @r-marques

**Comment by r-marques** [comment]
done in #25
