### ISSUE TITLE
Revisit __str__ method

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb-common#37]
At one point I decided that `str()` is super useful when signing transactions internally.
Now, I just used it externally and had to find out that it removes all signatures (which is obviously quite weird in some use cases).

Solution:
- Have a to-string method internally that gets rid of the signatures
- Have a to-string method externally that just deserializes the transaction 1:1

**Comment by r-marques** [comment]
This issue was moved to bigchaindb/bigchaindb#718
