### ISSUE TITLE
Rename `data_id` in the Metadata and Asset models

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb-common#39]
I find the name `data_id` confusing in both the `Metadata` and `Asset` model.
Since they are already inside a namespace I propose to rename `data_id` to `id`.
This way we have:
- `Transaction.id`
- `Transaction.metadata.id`
- `Transaction.asset.id`

**Comment by ssadler** [comment]
I had a thought on this earlier, it might be good to design the naming of hashes in such a way that distinguishes between UUIDs and fingerprints, seeing as they are different and have different use cases, but can sometimes be confused (see for example #43). It's maybe not a big problem right now, but if we're going to change it we could use `[metadata|asset].uuid`.

edit: uuid would be even better

**Comment by sbellem** [comment]
As an aside, we may want to consider using a different name than `id` since it is Python built-in function. It would leave no chance for ambiguity to arise.

**Comment by r-marques** [comment]
This issue was moved to bigchaindb/bigchaindb#717
