### ISSUE TITLE
CREATE transaction should support multiple owners in implicit condition

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb-common#56]
When creating a `CREATE` transaction, currently [only the first `owner_before` is taken as the "issuer" of the asset](https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L412).

Instead all `owners_before` should be taken into account and required to sign the transaction `thresholdOfThresholdCondition == len(owners_before)`

//cc @r-marques @sbellem

**Comment by r-marques** [comment]
This issue was moved to bigchaindb/bigchaindb#710
